# Generated by Django 3.1.1 on 2020-10-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('start_bid', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
